"""
Django settings for nebenet project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import django_extensions
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#User
AUTH_USER_MODEL = 'nebenet_app.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7g6vcgr29@rf+fkcbcx6$ydmq9zv%(ah@90^asf^z0)&j*4nz'

# SECURITY WARNING: don't run with debug turned on in production! 
#Cuando está en Falso, static files NO VAN A CARGAR xd
DEBUG = True
#DEBUG = False
ALLOWED_HOSTS = ['*']

#Seguridad
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_PATH = '/;HttpOnly'
#CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'
CORS_ORIGIN_ALLOW_ALL = True

# Content Security Policy

CSP_IMG_SRC = ("'self'",'localhost','https://use.fontawesome.com')

CSP_STYLE_SRC = ("'self'",'localhost','https://cdnjs.cloudflare.com')

CSP_SCRIPT_SRC = ("'self'",'localhost', 'https://use.fontawesome.com','https://maps.googleapis.com')

CSP_FONT_SRC = ("'self'",'localhost', 'https://fonts.googleapis.com',
                'https://cdnjs.cloudflare.com',
                'https://use.fontawesome.com',
                'https://www.google.com',
                'https://stackpath.bootstrapcdn.com',
                'https://fonts.gstatic.com')

CSP_STYLE_SRC_ELEM = ("'self'",'localhost', 'https://fonts.googleapis.com',
                'https://cdnjs.cloudflare.com',
                'https://fontawesome.com',
                'https://use.fontawesome.com',
                'https://www.google.com',
                'https://stackpath.bootstrapcdn.com',
                "'sha256-Jc7XaRBVYMy6h6FvjL32miHrOGOxYV+OP4swZ/9Gysw='",
                "'sha256-sYu/25NU93kGpqF4iAS8RqqmKvI/Mdk6QYKcIW+5ZuI='")

CSP_FRAME_SRC = ("'self'",'localhost', 'https://fonts.googleapis.com',
                'https://cdnjs.cloudflare.com',
                'https://fontawesome.com',
                'https://use.fontawesome.com',
                'https://www.google.com',
                "'sha256-Jc7XaRBVYMy6h6FvjL32miHrOGOxYV+OP4swZ/9Gysw='",
                "'sha256-sYu/25NU93kGpqF4iAS8RqqmKvI/Mdk6QYKcIW+5ZuI='")

CSP_STYLE_SRC_ATTR = ("'self'",'localhost', 'https://fonts.googleapis.com',
                'https://cdnjs.cloudflare.com',
                'https://fontawesome.com',
                'https://use.fontawesome.com',
                'https://www.google.com',
                'https://stackpath.bootstrapcdn.com',
                "'sha256-Jc7XaRBVYMy6h6FvjL32miHrOGOxYV+OP4swZ/9Gysw='",
                "'sha256-I+QFOcT3LDOlEFeJu7TbhV9HTRNN5nU7b/hvsQ3lSzU='",
                "'sha256-sYu/25NU93kGpqF4iAS8RqqmKvI/Mdk6QYKcIW+5ZuI='")

CSP_STYLE_SRC_ELEM = ("'self'",'localhost', 'https://fonts.googleapis.com',
                'https://cdnjs.cloudflare.com',
                'https://fontawesome.com',
                'https://use.fontawesome.com',
                'https://stackpath.bootstrapcdn.com',
                'https://www.google.com',
                "'sha256-Jc7XaRBVYMy6h6FvjL32miHrOGOxYV+OP4swZ/9Gysw='",
                "'sha256-sYu/25NU93kGpqF4iAS8RqqmKvI/Mdk6QYKcIW+5ZuI='")

CSP_FRAME_ANCESTORS = ("'self'")

CSP_BASE_URI = ("'self'")

CSP_SANDBOX = ('allow-modals','allow-scripts', 'allow-forms', 'allow-same-origin')

CSP_REPORT_URI = ("'self'",'localhost')

CSP_REQUIRE_SRI_FOR = ("'self'",'localhost')

##CSP_FORM_ACTION = ("'self'",'localhost')

CSP_INCLUDE_NONCE_IN = ['script-src']

# Application definition

INSTALLED_APPS = [
    'nebenet_app.apps.NebenetAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'location_field.apps.DefaultConfig',
    'crispy_forms',
]
CRISPY_TEMPLATE_PACK = 'uni_form'
#Maps
LOCATION_FIELD = {
    'map.provider': 'openstreetmap',
    'search.provider': 'nominatim',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'nebenet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nebenet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

####################Archivos#################################################3
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_env","static_root")
MEDIA_ROOT = 'media/'
MEDIA_URL = 'media/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,"static"),
]
#Redirects after login

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

#COntra
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'