# Generated by Django 4.1.5 on 2023-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='COMPONENT',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('Scheda madre', 'Scheda madre'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('m.2', 'M.2'), ('ram', 'RAM'), ('caso', 'Caso'), ('Alimentazione elettrica', 'Alimentazione elettrica'), ('ventilazione', 'Ventilazione'), ('periferica', 'Periferica'), ('N/A', 'none')], default='none', max_length=23, null=True, verbose_name='Component*'),
        ),
    ]
