# Generated by Django 4.2.1 on 2023-05-14 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_text', models.CharField(max_length=1000, verbose_name='Descrivi il tuo problema*')),
                ('ti_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti_mail', models.EmailField(max_length=254, verbose_name='Contatto email*')),
                ('ti_title', models.CharField(max_length=1000, verbose_name='Titolo*')),
                ('Problema', models.CharField(max_length=1000, verbose_name='Descrivi il tuo problema*')),
                ('ti_img', models.ImageField(blank=True, upload_to='', verbose_name='Aggiungi uno screenshot (facoltativo)')),
                ('ti_personal', models.BooleanField(verbose_name='Trattamento dei dati personali(Obbligatorio)*')),
                ('ti_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sc_pro',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sc_user',
        ),
        migrations.AddField(
            model_name='product',
            name='pro_price_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_salenumber',
            field=models.PositiveIntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ti_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebenet_app.product'),
        ),
        migrations.AddField(
            model_name='coment',
            name='co_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebenet_app.ticket'),
        ),
        migrations.AddField(
            model_name='coment',
            name='co_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nebenet_app.category'),
        ),
    ]
