# Generated by Django 4.1.5 on 2023-03-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0002_product_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='COMPONENT',
            new_name='pro_type',
        ),
    ]
