# Generated by Django 4.2.1 on 2023-05-23 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0002_category_coment_order_ticket_remove_cart_sc_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_characteristics',
            field=models.TextField(max_length=3000, verbose_name='Caratteristiche'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_description',
            field=models.TextField(max_length=3000, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo novo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_sale',
            field=models.BooleanField(verbose_name='Compila se vuoi fare un offerta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_salenumber',
            field=models.PositiveIntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='offerta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Problema',
            field=models.TextField(max_length=1000, verbose_name='Descrivi il tuo problema*'),
        ),
    ]
