# Generated by Django 4.1.5 on 2023-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0003_rename_component_product_pro_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('Scheda madre', 'Scheda madre'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('m.2', 'M.2'), ('ram', 'RAM'), ('caso', 'Caso'), ('Alimentazione elettrica', 'Alimentazione elettrica'), ('ventilazione', 'Ventilazione'), ('periferica', 'Periferica'), ('computer', 'Computer'), ('laptop', 'computer portatile'), ('N/A', 'none')], default='none', max_length=23, null=True, verbose_name='Component*'),
        ),
    ]
