# Generated by Django 4.1.5 on 2023-03-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0004_alter_product_pro_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
