# Generated by Django 4.1.5 on 2023-04-04 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0005_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti_issue', models.CharField(max_length=1000)),
                ('ti_img', models.ImageField(blank=True, upload_to='')),
                ('ti_personal', models.BooleanField()),
                ('ti_time', models.DateTimeField(auto_now=True)),
                ('ti_mail', models.ManyToManyField(to='nebenet_app.product')),
                ('ti_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
