# Generated by Django 4.1.5 on 2023-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ti_issue',
        ),
        migrations.AddField(
            model_name='ticket',
            name='Problema',
            field=models.CharField(default='a', max_length=1000, verbose_name='Descrivi il tuo problema*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ti_img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Aggiungi uno screenshot (facoltativo)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ti_personal',
            field=models.BooleanField(verbose_name='Trattamento dei dati personali*'),
        ),
    ]
