# Generated by Django 4.1.5 on 2023-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0007_remove_ticket_ti_issue_ticket_problema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ti_mail',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ti_mail',
            field=models.EmailField(default='jaja@mail.com', max_length=254, verbose_name='Contatto email*'),
            preserve_default=False,
        ),
    ]
