# Generated by Django 4.1.5 on 2023-04-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0008_remove_ticket_ti_mail_ticket_ti_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ti_title',
            field=models.CharField(default='a', max_length=1000, verbose_name='Titolo*'),
            preserve_default=False,
        ),
    ]
