# Generated by Django 4.1.5 on 2023-04-05 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0009_ticket_ti_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_text', models.CharField(max_length=1000, verbose_name='Descrivi il tuo problema*')),
                ('ti_time', models.DateTimeField(auto_now=True)),
                ('co_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebenet_app.ticket')),
                ('co_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
