# Generated by Django 4.1.5 on 2023-04-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0010_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='co_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nebenet_app.ticket'),
        ),
    ]
