# Generated by Django 4.1.5 on 2023-04-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0011_alter_coment_co_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='co_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebenet_app.ticket'),
        ),
    ]
