# Generated by Django 4.1.5 on 2023-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0012_alter_coment_co_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ti_personal',
            field=models.BooleanField(verbose_name='Trattamento dei dati personali(Obbligatorio)*'),
        ),
    ]
