# Generated by Django 4.1.5 on 2023-04-26 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0014_alter_product_pro_salenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_salenumber',
            field=models.PositiveIntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
