# Generated by Django 4.1.5 on 2023-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0015_alter_product_pro_salenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_price_before',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
