# Generated by Django 4.1.5 on 2023-04-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0016_product_pro_price_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_price_before',
            new_name='pro_price_after',
        ),
    ]
