# Generated by Django 4.1.5 on 2023-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebenet_app', '0017_rename_pro_price_before_product_pro_price_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_price_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
